// SPDX-License-Identifier: GPL-2.0+

#ifndef HID_IDS_H_FILE
#define HID_IDS_H_FILE

#define USB_VENDOR_ID_BETOP 0x20bc
#define USB_DEVICE_ID_BETOP_T6_USB 0x500c
#define USB_DEVICE_ID_BETOP_T6_ADAPTER 0x500d
#define USB_DEVICE_ID_BETOP_T6_USB_WITH_AUDIO 0x500e
#define USB_DEVICE_ID_BETOP_T6_ADAPTER_WITH_AUDIO 0x500f

#endif